spring.application.name=tender-process-service-scm
server.port=9073

eureka.client.service-url.defaultZone=http://service-registry:8080/service-registry-scm/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=tender-process-service
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/e_eiis
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
