spring.application.name=tender-process-service-scm

#local
#server.port=9083
 
#live
server.port=9073
server.servlet.context-path=/tender-process-service-scm
#Local
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#Live
eureka.client.service-url.defaultZone=http://localhost:9070/service-registry-scm/eureka/
 
spring.datasource.url=jdbc:postgresql://localhost:5432/e_eiis
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public
activiti.database-schema=public
 
# Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
management.tracing.sampling.probability=1.0
otel.exporter.otlp.endpoint=http://localhost:4317

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# python report base URL
python.api.base.url=http://103.39.133.98:5001
