spring.application.name=tender-process-service-scm
server.port=9073

eureka.client.service-url.defaultZone=http://service-registry:8080/service-registry-scm/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=tender-process-service

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/e_eiis
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=5
eureka.client.initialInstanceInfoReplicationIntervalSeconds=5

python.api.base.url=http://103.39.133.98:5001
